#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["Training.Presentation.API/Training.Presentation.API.csproj", "Training.Presentation.API/"]
COPY ["Training.Application.Services/Training.Application.Services.csproj", "Training.Application.Services/"]
COPY ["Training.Application.Dto/Training.Application.Dto.csproj", "Training.Application.Dto/"]
COPY ["Training.Data.Domain/Training.Data.Domain.csproj", "Training.Data.Domain/"]
COPY ["Training.Data/Training.Data.csproj", "Training.Data/"]
COPY ["Training.Data.EF/Training.Data.EF.csproj", "Training.Data.EF/"]
RUN dotnet restore "Training.Presentation.API/Training.Presentation.API.csproj"
COPY . .
WORKDIR "/src/Training.Presentation.API"
RUN dotnet build "Training.Presentation.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Training.Presentation.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Training.Presentation.API.dll"]