// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training.Data.EF;

namespace Training.Data.EF.Migrations
{
    [DbContext(typeof(UnitOfWork))]
    [Migration("20200420014902_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Training.Data.Domain.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a4a9ff4-394f-49b9-993d-b195d18c2769"),
                            CreationDate = new DateTime(2020, 4, 19, 20, 49, 1, 603, DateTimeKind.Local).AddTicks(9135),
                            DirectedBy = "Bong Joon Ho",
                            Duration = 132,
                            Genre = "Comedy, Drama, Trhiller",
                            ModifiedDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(925),
                            Name = "Parasite"
                        },
                        new
                        {
                            Id = new Guid("54803936-48f3-4ea5-aa71-f1fb4cc3aab7"),
                            CreationDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(2670),
                            DirectedBy = "Sam Mendez",
                            Duration = 119,
                            Genre = "Drama, War",
                            ModifiedDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(2705),
                            Name = "1917"
                        },
                        new
                        {
                            Id = new Guid("d91406e4-bf02-4c0e-a719-6c4a44e49ee5"),
                            CreationDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(2720),
                            DirectedBy = "Martin Scorsese",
                            Duration = 209,
                            Genre = "Biography, Crime, Drama",
                            ModifiedDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(2722),
                            Name = "The Irishman"
                        },
                        new
                        {
                            Id = new Guid("45ffdb54-d251-4776-bb9a-499d3b5fd3d3"),
                            CreationDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(2725),
                            DirectedBy = "Quentin Tarantino",
                            Duration = 161,
                            Genre = "Comedy, Drama",
                            ModifiedDate = new DateTime(2020, 4, 19, 20, 49, 1, 605, DateTimeKind.Local).AddTicks(2726),
                            Name = "Once Upoin a Time... In Hollywood"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
