// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training.Data.EF;

namespace Training.Data.EF.Migrations
{
    [DbContext(typeof(UnitOfWork))]
    partial class UnitOfWorkModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Training.Data.Domain.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9c734cf-76f6-4db6-839a-013ff6bbc875"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4257),
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4296),
                            Name = "Studio 1"
                        },
                        new
                        {
                            Id = new Guid("4328e74c-d820-4f6d-8fb0-fd49a552d65d"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4949),
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4954),
                            Name = "Universal Studios"
                        },
                        new
                        {
                            Id = new Guid("1d3e5008-5c35-4180-a898-55c5f5ca7fe8"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4978),
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4979),
                            Name = "Studio 3"
                        },
                        new
                        {
                            Id = new Guid("bce0d965-1fe6-46e7-bc4c-94ac3628091f"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4983),
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 656, DateTimeKind.Local).AddTicks(4984),
                            Name = "Studio 4"
                        });
                });

            modelBuilder.Entity("Training.Data.Domain.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StudioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eecfad93-dcfc-4d2c-bd74-dd5596eae957"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 653, DateTimeKind.Local).AddTicks(5789),
                            DirectedBy = "Bong Joon Ho",
                            Duration = 132,
                            Genre = "Comedy, Drama, Trhiller",
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(1382),
                            Name = "Parasite",
                            StudioId = new Guid("d9c734cf-76f6-4db6-839a-013ff6bbc875")
                        },
                        new
                        {
                            Id = new Guid("b934d480-e363-45ed-b5d6-0a5ea661df6d"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(3400),
                            DirectedBy = "Sam Mendez",
                            Duration = 119,
                            Genre = "Drama, War",
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(3429),
                            Name = "1917",
                            StudioId = new Guid("4328e74c-d820-4f6d-8fb0-fd49a552d65d")
                        },
                        new
                        {
                            Id = new Guid("3b9320d0-10d6-4bce-a13c-a69531eac7fc"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(3455),
                            DirectedBy = "Martin Scorsese",
                            Duration = 209,
                            Genre = "Biography, Crime, Drama",
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(3457),
                            Name = "The Irishman",
                            StudioId = new Guid("1d3e5008-5c35-4180-a898-55c5f5ca7fe8")
                        },
                        new
                        {
                            Id = new Guid("13fabf95-683a-498e-95b4-a6daba175d72"),
                            CreationDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(3464),
                            DirectedBy = "Quentin Tarantino",
                            Duration = 161,
                            Genre = "Comedy, Drama",
                            ModifiedDate = new DateTime(2020, 4, 21, 1, 7, 37, 654, DateTimeKind.Local).AddTicks(3466),
                            Name = "Once Upoin a Time... In Hollywood",
                            StudioId = new Guid("1d3e5008-5c35-4180-a898-55c5f5ca7fe8")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
