//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEFProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        public int Id { get; set; }
        public string BookName { get; set; }
        public string Price { get; set; }
        public string Category { get; set; }
        public string AuthorName { get; set; }
        public string Edition { get; set; }
        public string BookCondition { get; set; }
        public string Available { get; set; }
    }
}
