//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPurchase
    {
        public int CustId { get; set; }
        public string Product { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int CustomerProfileCustId { get; set; }
    
        public virtual CustomerProfile CustomerProfile { get; set; }
    }
}
